<?php
$title = 'your Flights';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('flightressystem', array('action'=>'search'));?>">Add new Flight</a>
 </p>

 <table class="table">
 <tr>
     <th>Airline</th>
     <th>FlightNumber</th>
     <th>Aircraft</th>
     <th>Free seats</th>
     <th>Price </th>
     
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($flights as $flight) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($flight->getAirline());?></td>
     <td><?php echo $this->escapeHtml($flight->getFlightnumber());?></td>
          <td><?php echo $this->escapeHtml($flight->getAircraft());?></td>
     
          <td><?php echo $this->escapeHtml($flight->getFreeseats());?></td>
          <td><?php echo $this->escapeHtml($flight->getPrice());?></td>
     
     <td>
         <a href="<?php echo $this->url('flightressystem',
             array('action'=>'edit', 'id' => $flight->getId()));?>">Edit</a>
         <a href="<?php echo $this->url('flightressystem',
             array('action'=>'delete', 'id' => $flight->getId()));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>